map_file_path: "/home/rm/sentry_all/sentry_nav_3.0.3/src/navigation/sentry_slam/maps/map_20260129_162718.png"
scan_topic: "/scan"
map_resolution: 0.05
lidar_max_range: 8.0
max_iterations: 30
stop_search_threshold_f1: 50
